// let resume = {
//     name: "Samiran",
//     age: 20,
//     course: "B.C.A",
//     sem:5,
//     skills: "Depression , Teansion Lena",
    
//     greet: function(){
//     console.log(`Hello , This Side ${this.name}`)
// }
// }

// // console.log(resume)
// // console.log(resume.name)
// // console.log(resume["age"])

// // resume.skills = "Hardwork, Cricket"
// // console.log(resume)






// resume.city = "Purba Medinipur"

// // resume.greet = function(){
// //     console.log("hello")
// // }

// // console.log(resume.greet())


// // greet: function(){
//     //     console.log(`Hello , This Side ${this.name}`)
//     // }
//     // console.log(resume.greet())
//     console.log(resume.greet())



//     let resume = {
//     name: "Samiran",
//     age: 20,
//     course: "B.C.A",
//     sem:5,
//     skills: "Depression , Teansion Lena",
    
//     greet: function(){
//     console.log(`Hello , This Side ${this.name}`)
// } 

// }


let obj = {
    name:"Smairan",
    age:20,
    city :"East Medinipur",
    course:"B.C.A",
    sem:5,
    skills: "Hardwork, Cricket",
    EnNo:"24COA2BCA1160",

    greet:function(){
    console.log(`hey this side ${this.name} my enrollment no ${this.EnNo}`)
    }
}

obj.name =  "Smairan"
console.log(obj.greet())